install:
  - sudo apt-get update
  - sudo apt-get install puppet libxml2-dev libreadline-dev augeas-lenses libaugeas-dev 
  - sudo cp -R $TRAVIS_BUILD_DIR/spec/fixtures/augeas/etc/postfix /etc/
  - sudo cp $TRAVIS_BUILD_DIR/spec/fixtures/augeas/etc/init.d/postfix /etc/init.d/
language: ruby
bundler_args: --without development
script: "sudo -E bash -c \"PATH=$PATH; echo -n 'PATH: ' && echo $PATH && echo -n 'TRAVIS_BUILD_DIR: ' && echo $TRAVIS_BUILD_DIR && bundle install && bundle exec rake spec SPEC_OPTS='--format documentation' && puppet apply --modulepath=$TRAVIS_BUILD_DIR/spec/fixtures/modules --noop tests/init.pp\""
rvm:
  - 1.8.7
env:
  - PUPPET_GEM_VERSION="~> 2.7.0"
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email: false
